apiVersion: oos.dev/v1alpha1
kind: Entity
metadata: { name: PurchaseOrder, namespace: scm }
spec:
  nature: entity
  primaryKey: [orderId]
  properties:
    orderId: { type: String }
    status:
      type: String
      labels: { acme.assurance: reviewed }
