apiVersion: oos.dev/v1alpha3
kind: Ruleset
metadata: { name: gdpr-minimization, namespace: eu }
spec:
  owner: team:compliance
  targets:
    - atLeast: { gdpr.sensitivity: high }
  masks:
    - declassifier: tokenize
      to: { gdpr.sensitivity: low }
