apiVersion: oos.dev/v1alpha2
kind: Function
metadata: { name: approvePurchaseOrder, namespace: scm }
spec:
  runtime: wasm
  entrypoint: dist/approve.wasm
  effects:
    - writes: scm.PurchaseOrder.totalWithTax
      datasourceRef: postgres_erp
  endorsements:
    - endorser: attested
      attestation: attestations/approve.intoto.jsonl
