apiVersion: oos.dev/v1alpha1
kind: Binding
metadata: { name: warehouse, namespace: hr }
spec:
  targetEntity: hr.Employee
  datasourceRef: hr_db
  source: "public.tb_employee"
  properties:
    employeeId: "emp_id"
    baseSalary: "base_salary"
    bonus: "bonus"
    totalCompensation: "total_comp"
  materialization:
    payload:
      properties: [employeeId, totalCompensation]
