apiVersion: oos.dev/v1alpha17
kind: Dataset
metadata: { name: regiones, namespace: legal }
spec:
  owner: team:legal
  columns:
    id: { type: "String" }
    r: { type: "Struct<donde: Anchor, texto: String>" }
  changes: { mode: append }
