apiVersion: oos.dev/v1alpha16
kind: MediaCollection
metadata:
  name: contratos
  namespace: legal
  schema: archivo
  labels: { gdpr.sensitivity: high }
spec:
  owner: team:legal
  media: document
  formats: [pdf]
  from: { objectTable: s3_ventas.docs.contratos }
  virtual: true
