apiVersion: oos.dev/v1alpha4
kind: Entity
metadata: { name: Customer, namespace: crm }
spec:
  nature: entity
  primaryKey: [id]
  implements: [acme.Party, acme.Contactable]
  properties:
    id: { type: String }
    email: { is: acme.personalEmail }
    name: { is: acme.legalName }
