apiVersion: oos.dev/v1alpha8
kind: View
metadata: { name: por_pais, namespace: hr }
spec:
  owner: team:hr
  from: { view: empleados }
  fields:
    pais: pais
    total: "sum(salario)"
  groupBy: [pais]
