apiVersion: oos.dev/v1alpha1
kind: Entity
metadata: { name: Customer, namespace: hr, labels: { oos.maturity: STABLE } }
spec:
  nature: entity
  primaryKey: [customerId]
  uniqueKeys: [[email], [externalId]]
  properties:
    customerId: { type: String }
    externalId: { type: String }
    country:    { type: String, labels: { gdpr.sensitivity: none } }
    email:      { type: String, labels: { gdpr.sensitivity: low } }
