apiVersion: oos.dev/v1alpha17
kind: Dataset
metadata: { name: fichas, namespace: legal }
spec:
  owner: team:legal
  columns:
    id: { type: "String" }
    ficha: { type: "Struct<autor: Struct<nombre: String, rol: String>, huella: Vector<8>>" }
  changes: { mode: append }
