apiVersion: oos.dev/v1alpha8
kind: View
metadata: { name: v_erp, namespace: hr }
spec:
  owner: team:x
  from: { table: hr.tb_employee }
  fields:
    employeeId: emp_id
    nationalId: national_id
