apiVersion: oos.dev/v1alpha14
kind: View
metadata: { name: patron, namespace: hr }
spec:
  owner: team:hr
  dialect: duckdb
  sql: |
    SELECT id FROM hr.empleados WHERE dni LIKE '1%'
  columns:
    id: { type: String }
