apiVersion: oos.dev/v1alpha3
kind: Ruleset
metadata: { name: staff-quality, namespace: eu }
spec:
  owner: team:compliance
  targets:
    - implements: [acme.Employee]
  assertions:
    - id: sin-nulos
      metric: nullValues
      mustBe: 0
      dimension: completeness
      severity: error
