apiVersion: oos.dev/v1alpha17
kind: Dataset
metadata: { name: matrices, namespace: legal }
spec:
  owner: team:legal
  columns:
    id: { type: "String" }
    m: { type: "list<list<Float>>" }
  changes: { mode: append }
