apiVersion: oos.dev/v1alpha8
kind: Entity
metadata: { name: Employee, namespace: hr }
spec:
  nature: entity
  primaryKey: [employeeId]
  backedBy: empleados
  properties:
    employeeId: { type: String }
    alias:      { type: String }
