apiVersion: oos.dev/v1alpha8
kind: Table
metadata: { name: tb_employee, namespace: hr }
spec:
  datasource: hr_db
  object: "public.tb_employee"
  columns:
    emp_id: {}
    country: {}
  reads: { predicatePushdown: [eq, in, range], fullScan: cheap }
  changes: { mode: none }
