apiVersion: oos.dev/v1alpha10
kind: Action
metadata: { name: segmentar, namespace: ventas }
spec:
  over: ventas.clientes
  input:
    segmento: { type: String, required: true }
  sets:
    - writes: ventas.Cliente.segmento
      from: input.segmento
  call: ventas.editar
