apiVersion: oos.dev/v1alpha8
kind: View
metadata: { name: pedidos, namespace: ventas }
spec:
  owner: team:ventas
  from: { table: ventas.pedidos }
  fields:
    pedidoId: pedido_id
    fecha: fecha
    total: total
