apiVersion: oos.dev/v1alpha1
kind: Binding
metadata: { name: erp, namespace: hr }
spec:
  targetEntity: hr.Employee
  datasourceRef: hr_db
  source: "public.tb_employee"
  properties: { employeeId: "emp_id" }
  materialization:
    mode: passthrough
