apiVersion: oos.dev/v1alpha1
kind: Entity
metadata: { name: Employee, namespace: hr, labels: { oos.maturity: STABLE } }
spec:
  nature: entity
  primaryKey: [employeeId]
  properties:
    employeeId: { type: String }
    grade: { type: String, enum: [IC1, IC2, IC3, M1] }
