apiVersion: oos.dev/v1alpha2
kind: Function
metadata: { name: approvePurchaseOrder, namespace: scm }
spec:
  runtime: wasm
  entrypoint: dist/approve.wasm
  effects:
    - writes: scm.PurchaseOrder.status
      datasourceRef: postgres_erp
  endorsements:
    - endorser: humanApproval
      quorum: 2
