apiVersion: oos.dev/v1alpha1
kind: Entity
metadata: { name: Employee, namespace: hr }
spec:
  nature: entity
  primaryKey: [employeeId, departmentId]
  properties:
    employeeId:   { type: String }
    departmentId: { type: String }
