apiVersion: oos.dev/v1alpha8
kind: Table
metadata: { name: tb_employee, namespace: hr }
spec:
  datasource: hr_db
  object: "public.tb_employee"
  columns:
    email: {}
    emp_id: {}
    grade: {}
    manager_id: {}
  reads: { predicatePushdown: [eq], fullScan: cheap }
  changes: { mode: none }
