apiVersion: oos.dev/v1alpha16
kind: Dataset
metadata: { name: vectores, namespace: legal }
spec:
  owner: team:legal
  columns:
    id: { type: "String" }
    vector: { type: "Vector<768>" }
  changes: { mode: append }
