apiVersion: oos.dev/v1alpha1
kind: Binding
metadata: { name: erp, namespace: hr }
spec:
  targetEntity: hr.Shipment
  datasourceRef: hr_db
  source: "public.tb_shipment"
  properties:
    shipmentId: "shp_id"
    quantity: "qty"
  materialization:
    topology: {}
