apiVersion: oos.dev/v1alpha1
kind: Binding
metadata: { name: erp, namespace: hr }
spec:
  targetEntity: hr.Employee
  datasourceRef: erp
  source: "public.tb_employee"
  properties:
    employeeId: "emp_id"
    departmentId: "dept_id"
  materialization:
    topology: {}
    payload:
      # `salary` es una propiedad de la entidad y NO esta en el mapeo
      properties: [salary]
      freshnessSLA: 24h
