apiVersion: oos.dev/v1alpha3
kind: Ruleset
metadata: { name: nif, namespace: eu }
spec:
  owner: team:compliance
  targets:
    - atLeast: { gdpr.sensitivity: high }
  scopes:
    - id: own-department
      property: hr.Employee.departmentId
      matches: departmentId
  assertions:
    - id: sin-nulos
      metric: nullValues
      mustBe: 0
      severity: error
