apiVersion: oos.dev/v1alpha18
kind: Function
metadata: { name: repetir, namespace: ventas }
spec:
  runtime: python
  entrypoint: funciones/repetir.py:repetir
  input:
    dia: { type: Date, required: true }
  output: { type: String }
