apiVersion: oos.dev/v1alpha17
kind: Dataset
metadata: { name: facturas, namespace: legal }
spec:
  owner: team:legal
  columns:
    id: { type: "String" }
    factura: { type: "Struct<>" }
  changes: { mode: append }
